### ISSUE TITLE
Error accesing /users

### ISSUE THREAD

**Issue by miguelpdm** [SenseTecnic/node-red-contrib-users#23]
Hi,
Thanks for your work, I really like it.
I was testing the component, and i suddenly started geting this error in /users:
TypeError: Cannot read properties of undefined (reading 'split')
    at getTokenFromRequest (/data/node_modules/node-red-contrib-users-jwt/users.js:16:42)
    at verifyJwt (/data/node_modules/node-red-contrib-users-jwt/users.js:24:19)
    at /data/node_modules/node-red-contrib-users-jwt/users.js:133:19
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:144:13)
    at appendTrailingSlash (/data/node_modules/node-red-contrib-users-jwt/users.js:106:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)

I was just testing with postman and now I'm stuck at this point.
KR

**Comment by Halli2024** [comment]
Same problem for me. Seemed to work yesterday and today I only get this error.

TypeError: Cannot read properties of undefined (reading 'split')
    at getTokenFromRequest (/home/developer/.node-red/node_modules/node-red-contrib-users-jwt/users.js:16:42)
    at verifyJwt (/home/developer/.node-red/node_modules/node-red-contrib-users-jwt/users.js:24:19)
    at /home/developer/.node-red/node_modules/node-red-contrib-users-jwt/users.js:133:19
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:144:13)
    at appendTrailingSlash (/home/developer/.node-red/node_modules/node-red-contrib-users-jwt/users.js:106:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    
Node-red running on raspberry pi.
